:PROPERTIES:
:ID:       429cecd9-0996-4cba-8259-42c75b2a2c25
:END:
- tag :: [[id:17860e5d-2718-45dc-a28a-374b3c1f73a2][奇门遁甲]]
#+title: 奇门遁甲预测的判断依据

* 奇门遁甲预测的判断依据
** 十干克应
十干克应，就是十个天干在天盘和地盘相遇之后的克应关系。由于遁甲，所以六甲主要以六仪为代表而看其克应关系。
*** 甲子戊
=天盘甲子戊：=
临戊：甲甲比肩，诸事不吉，道路遇到阻塞。以守为好，名为伏吟，主慢。
临乙奇：戊加乙，由于甲和乙都居东方，为青龙木。所以叫青龙和会，门吉也吉，门凶也凶。
临丙奇：戊加丙，青龙甲木，丙为阳火，甲木生助丙火，故为青龙返首，为事所谋，大吉大利。但是碰到迫墓刑击，吉事成凶。
临丁奇：戊加丁，青龙甲木也生丁火，所以为青龙曜明，见大人、贵人、求功名、为事吉利。但是碰到墓迫，容易招惹是非。
临甲戌己：由于戌为戊土之墓，故为贵人入狱，公私皆不利。
临甲申庚：即戊加庚、因为值符最怕庚金克杀，故为值符飞宫，吉事不吉，凶事更凶，求财没有利益，测病也主凶，同时甲庚相冲，飞宫也主换地方。
临甲午辛：辛金克甲木，子午相冲，所以是青龙折足。吉门有生助，尚能谋事，如果逢凶门，主招灾、矢财或者有足疾、折伤。
临甲辰壬：因为壬为天牢，甲为青龙，所以为青龙入天牢，无论阴阳都不吉利。
临甲寅癸：因为甲为青龙，癸为华盖，又为天网，所以为青龙华盖，又因为戊癸相合，所以逢吉门吉利，可招福临门。逢凶门者事多不利，为凶

*** 乙奇
=天盘乙奇：=
临甲子戊：即乙加戊，乙木克戊土，为 =阴害阳门= （因为戊为阳为天门），利于阴人、阴事，不利于阳人阳事，门吉尚可谋为，门迫则破财伤人。
临乙奇：乙乙比肩，为日奇伏吟，不宜见上层领导、贵人，不宜求名求利，只宜安分守己。
临丙奇：乙木生丙火，为奇仪顺遂，吉星迁官晋升，凶星夫妻反目
临丁奇：乙加丁，为奇仪相佐，最利文书、考试、百事可为。
临甲戌己：乙加己，因戌为乙木之墓，故为日奇入墓，被土暗昧，门凶事必凶，得生开二吉门为地遁。
临甲申庚：乙加庚，庚金克刑乙木，故为日奇被刑，为争讼财产，夫妻怀有私意。
临甲午辛：乙加辛，乙为青龙，辛为白虎，乙木被辛金冲克而逃走，故为青龙逃走，人亡财破，奴仆拐带，六畜皆伤。测婚为女逃男。
临甲辰壬：乙加壬，为 =日奇入地= ，尊卑悖乱，官讼是非，有人谋害之事
临甲寅癸：乙加癸，为华盖逢星，遁迹修道，隐匿藏形，躲灾避难为吉。

*** 丙奇
=天盘丙奇：=
临甲子戊：丙加戊，甲为丙火之母，丙火回到母亲身边，好似飞鸟归巢，故名鸟跌穴，百事吉，事业可为，可谋大事。
临乙：丙加乙，为日月并行，公谋私为皆为吉。
临丙：丙加丙，为月奇悖师，文书逼迫，破耗遗失
临丁：丙加丁，为星奇朱雀，贵人文书吉利，常人平静安乐，得三吉门为天遁。
临甲戌己：丙加己，因丙火入戌墓，故为火悖入刑，因人刑杖，文书不行，吉门得吉，凶门转凶。
临甲申庚：丙加庚，丙加庚，为荧入太白，门户破败，盗贼耗失，事业亦凶。
临甲午辛：丙加辛，因丙辛相合，故为谋事能成，为疾病人不凶。
临甲辰壬：丙加壬，为火入天罗，壬水冲克丙火，故为客不利。
临甲寅癸：丙加癸，为华盖悖师，阴人害事，灾祸频生。

*** 丁奇
=天盘丁奇=
临甲子戊：丁加戊，甲为丁
